version: '3'

services:
  springboot-docker-compose-app-container:
    image: helloWord:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data/springboot-docker-compose-app
    ports:
      - "8080:8081"